# Generated by Django 3.2.8 on 2021-11-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safety', '0002_delete_safetyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('like', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
