# Generated by Django 3.2.8 on 2021-11-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0005_alter_commentsection_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='attached_report',
            field=models.IntegerField(default=0),
        ),
    ]
