# Generated by Django 3.2.8 on 2021-11-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0006_commentsection_attached_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='mod_Locked',
            field=models.BooleanField(default=False),
        ),
    ]
