# Generated by Django 3.2.8 on 2021-11-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0007_auto_20211104_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNameDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
